"""add_skills_and_category_to_projects

Revision ID: 252c0dfd11c0
Revises: f81785d70c71
Create Date: 2025-12-31 16:03:26.487065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252c0dfd11c0'
down_revision = 'f81785d70c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
